### ISSUE TITLE
Invalid Product link

### ISSUE THREAD

**Issue by pajasry** [OLIMEX/ESP32-S2-DevKit-LiPo-USB#1]
Hi, 
I bounced at your repository and found that the product link points to another product. It will be great if it could point to correct item.

https://github.com/OLIMEX/ESP32-S2-DevKit-LiPo-USB/blob/e5b7f0caae41b40c24599ce29c55959507c270ee/README.md?plain=1#L5

**Comment by TsvetanUsunov** [comment]
thanks for the note, this is fixed now
